import React from 'react';
import Card from '@material-ui/core/Card';
import Avatar from '@material-ui/core/Avatar';
import classNames from 'classnames';
import TextField from '@material-ui/core/TextField';
import Typography from '@material-ui/core/Typography';
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';
import MainContainer from '../../components/MainContainer';
import ChatUI from './UI';

class ChatPageContainer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      messages: JSON.parse(localStorage.getItem('messages')) || [],
      message: '',
      intervalId: undefined
    };
    this.handleChange = this.handleChange.bind(this);
    this.onEnter = this.onEnter.bind(this);
    this.onKeyPress = this.onKeyPress.bind(this);

  }
  componentDidMount() {
    const intervalId = setInterval(() => {
      this.onEnter(true)();
    }, 15000);
    this.setState({ intervalId });
  }
  componentWillUnmount() {
    clearInterval(this.state.intervalId);
  }
  handleChange = (name) => (event) => {
    this.setState({
      [name]: event.target.value
    })
  }
  onEnter = (autoGenerated) => () => {
    if (this.state.message || autoGenerated) {
      const { message } = this.state.message;
      let messages = [...this.state.messages];
      messages.push({
        autoGenerated,
        message: autoGenerated ?
          'This is an auto generated message' : this.state.message
      });
      this.setState({
        messages,
        message: autoGenerated ? this.state.message : ''
      });
      localStorage.setItem('messages', JSON.stringify(messages));
    }
  }
  onKeyPress(ev) {
    if (ev.key === 'Enter') {
      this.onEnter();
    }
  }
  render() {
    console.log(this.state);
    return (
      <ChatUI
        {...this.state}
        handleChange={this.handleChange}
        onEnter={this.onEnter(false)}
        onKeyPress={this.onKeyPress}
      />
    )
  }
}
export default ChatPageContainer;