import React from 'react';
import Card from '@material-ui/core/Card';
import Avatar from '@material-ui/core/Avatar';
import classNames from 'classnames';
import TextField from '@material-ui/core/TextField';
import Typography from '@material-ui/core/Typography';
import Button from '@material-ui/core/Button';
import { withStyles } from '@material-ui/core/styles';
import MainContainer from '../../components/MainContainer';
import Icon from '@material-ui/core/Icon';
import Chip from '@material-ui/core/Chip';
import Paper from '@material-ui/core/Paper';

const styles = {
  card: {
    minWidth: 350,
    padding: 20,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '80%'
  },
  avatar: {
    margin: 10,
  },
  bigAvatar: {
    width: 80,
    height: 80,
  },
  textField: {
    marginRight: 20
  },
  button: {
    marginTop: 20
  },
  error: {
    color: 'red'
  }
};

const ChatPageUI = (props) => {
  const { classes, message, messages, handleChange, onEnter, onKeyPress } = props;
  return (
    <MainContainer>
      <Card className={classes.card}>
        <Paper style={{ width: '100%', overflow: 'auto', flexDirection: 'column', display: 'flex', flex: 1 }}>
          {
            messages.map((each) => (
              <Chip
                label={<Typography style={{  }}>{each.message}</Typography>}
                style={{ margin: 5, minHeight: 30, height: 30 }}
                href="#chip"
                variant="outlined"
                color={each.autoGenerated ? 'secondary' : 'primary'}
              />
              // <div style={{ textAlign: each.autoGenerated ? 'left' : 'right' }}>{each.message}</div>
            ))
          }
        </Paper>
        <div style={{
          flexDirection: 'row',
          width: '100%',
          display: 'flex',
          alignItems: 'center'
        }}>
          <TextField
            style={{ flex: 1 }}
            className={classes.textField}
            id="outlined-name"
            label="Message"
            value={message}
            onChange={handleChange('message')}
            margin="normal"
            fullWidth
            variant="outlined"
            onKeyPress={onKeyPress}
          />
          <Button onClick={onEnter} variant="fab" color="primary">
            <Icon >send</Icon>
          </Button>
        </div>
      </Card>
    </MainContainer>
  )
}
export default withStyles(styles)(ChatPageUI);